name: frontend-runner

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      
      - name: Build Docker Image
        run: |
          cd C:\fontys\Semester2\Programming\cl-cd_pipelines\testpush\DockerPipelineTestgo
          git clone https://github.com/bramplatier/DockerPipelineTestgo
          cd .\DockerPipelineTestgo
          docker build --tag dockergoimage .
      
      - name: Run Docker Container
        run: |
          docker run -d -p 8080:8080 dockergoimage
